AWSTemplateFormatVersion: 2010-09-09
Description: Trend Cloud One SecurityHub Onboard Stack

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: 'Please adjust the fields below as required for deployment.'
      Parameters:
      - CloudOneApiKey
      - CloudOneRegion

Parameters:
  CloudOneApiKey:
    Description: Cloud One API Key. You can learn more about it at https://cloudone.trendmicro.com/docs/identity-and-account-management/c1-api-key/
    Type: String
    NoEcho: true
  CloudOneRegion:
    Description: "Cloud One region to be used, default: us-1"
    Default: "us-1"
    Type: String

Resources:
    LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Path: "/"
        ManagedPolicyArns:
          - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Code:
          S3Bucket: sechub-abi-test
          S3Key: handler.zip
        Handler: handler.lambda_handler
        Role: !GetAtt LambdaExecutionRole.Arn
        Runtime: python3.9
        Timeout: 300
        Architectures:
          - arm64 
        Environment:
          Variables:
            CloudOneApiKey: !Ref CloudOneApiKey
            CloudOneRegion: !Ref CloudOneRegion
        