project_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln84e80y'
project_name: 'ABI Trend Cloudone'
project_code: '133f6c57-59b8-4fae-9356-4ce8aca34922'
project_type: 'ABI CloudFormation Project Type'
partner_name: 'Trendmicro'
launch_date: '2023-10-04'
repo_name: 'cfn-abi-trend-cloudone'
templates_info:
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln83zxxr'
    file_name: 'templates/main.template.yaml'
    count_flag: 'true'
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln83zypo'
    file_name: 'templates/trend-cloudone-onboard/cloudone.template.yaml'
    count_flag: 'false'
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln83zzhl'
    file_name: 'templates/trend-cloudone-onboard/workloadsecurity.template.yaml'
    count_flag: 'false'
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln84009i'
    file_name: 'templates/trend-cloudone-onboard/vision-one-enrollment.template.yaml'
    count_flag: 'false'
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln84011g'
    file_name: 'templates/trend-cloudone-onboard/main.template.yaml'
    count_flag: 'false'
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln8401ta'
    file_name: 'templates/trend-cloudone-onboard/vision-one-generate-enrollment-token.yaml'
    count_flag: 'false'
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln8402l6'
    file_name: 'templates/trend-cloudone-onboard/cloudtrail.template.yaml'
    count_flag: 'false'
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln8403d2'
    file_name: 'templates/common/get-cloudone-region-and-account.template.yaml'
    count_flag: 'false'
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln84044z'
    file_name: 'templates/trend-cloudone-ws-ssm-association/AgentDeploymentScriptParse.template.yaml'
    count_flag: 'false'
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln8404ws'
    file_name: 'templates/trend-cloudone-ws-ssm-association/main.template.yaml'
    count_flag: 'false'
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-AjPZXDiXyrPBYf1SiahJE-ln84bcm8'
    file_name: 'templates/trend-cloudone-ws-ssm-association/c1ws-ssm-orgs.template.yaml'
    count_flag: 'false'