project:
  name: cfn-abi-trend-cloudone-ws-ssm-deployment
  owner: justin_perkins@trendmicro.com
  package_lambda: false
  shorten_stack_name: true
  regions:
  - us-east-1

tests:
  examination1:
    parameters:
      DeploymentTargets: 'ou-br9h-5q1xhx7c,ou-br9h-pna1itsq'
      dsActivationUrl: $[taskcat_ssm_/trend/activation_url]
      dsManagerUrl: $[taskcat_ssm_/trend/manager_url]
      dsTenantId: $[taskcat_ssm_/trend/tenant_id]
      dsToken: $[taskcat_ssm_/trend/ds_token]
      AccountAdminStatus: DELEGATED_ADMIN
    regions:
    - us-east-1
    template: templates/trend-cloudone-ws-ssm-association/c1ws-ssm-orgs.template.yaml

