project:
  name: cfn-abi-trend-cloudone
  owner: raphael_bottino@trendmicro.com #We need a DL for this.
  package_lambda: true
  shorten_stack_name: true
  regions:
  - us-east-1

tests:
  all-false: # No integration, only common resources.
    parameters:
      DeployCloudTrailIntegration: "False"
      DeploySSMIntegration: "False"
      CloudOneApiKey: $[taskcat_ssm_/trend/cloudone_svc_apikey]
      OrganizationId: $[taskcat_ssm_/trend/organization_id]
      VisionOneAuthenticationToken: $[taskcat_ssm_/trend/visionone_authentication_token]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: $[taskcat_project_name]
      ExistingOrganizationalCloudtrailBucketName: $[taskcat_ssm_/trend/existing_organizational_cloudtrail_bucket_name]
    regions:
    - us-east-1
    template: templates/main.template.yaml
  cloudtrail:
    parameters:
      DeployCloudTrailIntegration: "True"
      DeploySSMIntegration: "False"
      DeploySecurityHubIntegration: "False"
      CloudOneApiKey: $[taskcat_ssm_/trend/cloudone_svc_apikey]
      OrganizationId: $[taskcat_ssm_/trend/organization_id]
      VisionOneAuthenticationToken: $[taskcat_ssm_/trend/visionone_authentication_token]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: $[taskcat_project_name]
      ExistingOrganizationalCloudtrailBucketName: $[taskcat_ssm_/trend/existing_organizational_cloudtrail_bucket_name]
    regions:
    - us-east-1
    template: templates/main.template.yaml
  ws-ssm-deployment:
    parameters:
      DeployCloudTrailIntegration: "False"
      DeploySSMIntegration: "True"
      DeploySecurityHubIntegration: "False"
      CloudOneApiKey: $[taskcat_ssm_/trend/cloudone_svc_apikey]
      OrganizationId: $[taskcat_ssm_/trend/organization_id]
      AccountAdminStatus: SELF
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: $[taskcat_project_name]
    regions:
    - us-east-1
    template: templates/main.template.yaml
  security-hub:
    parameters:
      DeployCloudTrailIntegration: "False"
      DeploySSMIntegration: "False"
      DeploySecurityHubIntegration: "True"
      CloudOneApiKey: $[taskcat_ssm_/trend/cloudone_svc_apikey]
      OrganizationId: $[taskcat_ssm_/trend/organization_id]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: $[taskcat_project_name]
      EnableSecurityHub: "false"
    regions:
    - us-east-1
    template: templates/main.template.yaml
  security-hub-no-abi:
    parameters:
      DeployCloudTrailIntegration: "False"
      DeploySSMIntegration: "False"
      DeploySecurityHubIntegration: "True"
      OrganizationId: $[taskcat_ssm_/trend/organization_id]
      CloudOneApiKey: $[taskcat_ssm_/trend/cloudone_svc_apikey]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: $[taskcat_project_name]
      EnableSecurityHub: "false"
    regions:
    - us-east-1
    template: templates/main.template.yaml
  all-integrations:
    parameters:
      DeployCloudTrailIntegration: "True"
      DeploySSMIntegration: "True"
      DeploySecurityHubIntegration: "True"
      CloudOneApiKey: $[taskcat_ssm_/trend/cloudone_svc_apikey]
      OrganizationId: $[taskcat_ssm_/trend/organization_id]
      VisionOneAuthenticationToken: $[taskcat_ssm_/trend/visionone_authentication_token]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: $[taskcat_project_name]
      ExistingOrganizationalCloudtrailBucketName: $[taskcat_ssm_/trend/existing_organizational_cloudtrail_bucket_name]
      AccountAdminStatus: DELEGATED_ADMIN
    regions:
    - us-east-1
    template: templates/main.template.yaml
