project:
  name: cfn-abi-trend-cloudone
  owner: raphael_bottino@trendmicro.com #We need a DL for this.
  package_lambda: true
  shorten_stack_name: true
  regions:
  - us-east-1

tests:
  all-false: # No integration, only common resources.
    parameters:
      DeployCloudTrailIntegration: "False"
      DeploySSMIntegration: "False"
      CloudOneApiKey: $[taskcat_ssm_/trend/cloudone_svc_apikey]
      VisionOneAuthenticationToken: $[taskcat_ssm_/trend/visionone_authentication_token]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: $[taskcat_project_name]
      ExistingOrganizationalCloudtrailBucketName: $[taskcat_ssm_/trend/existing_organizational_cloudtrail_bucket_name]
    regions:
    - us-east-1
    template: templates/main.template.yaml
  t1: # CloudTrail integration only.
    parameters:
      DeployCloudTrailIntegration: "True"
      DeploySSMIntegration: "False"
      CloudOneApiKey: $[taskcat_ssm_/trend/cloudone_svc_apikey]
      VisionOneAuthenticationToken: $[taskcat_ssm_/trend/visionone_authentication_token]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: $[taskcat_project_name]
      ExistingOrganizationalCloudtrailBucketName: $[taskcat_ssm_/trend/existing_organizational_cloudtrail_bucket_name]
    regions:
    - us-east-1
    template: templates/main.template.yaml
  ws-ssm-deployment:
    parameters:
      DeployCloudTrailIntegration: "False"
      DeploySSMIntegration: "True"
      CloudOneApiKey: $[taskcat_ssm_/trend/cloudone_svc_apikey]
      AccountAdminStatus: SELF
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: $[taskcat_project_name]
    regions:
    - us-east-1
    template: templates/main.template.yaml
  cloudtrail-and-ssm-integration:
    parameters:
      DeployCloudTrailIntegration: "True"
      DeploySSMIntegration: "True"
      CloudOneApiKey: $[taskcat_ssm_/trend/cloudone_svc_apikey]
      VisionOneAuthenticationToken: $[taskcat_ssm_/trend/visionone_authentication_token]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: $[taskcat_project_name]
      ExistingOrganizationalCloudtrailBucketName: $[taskcat_ssm_/trend/existing_organizational_cloudtrail_bucket_name]
      AccountAdminStatus: DELEGATED_ADMIN
    regions:
    - us-east-1
    template: templates/main.template.yaml
